version: "3.2"
services:
  db:
    image: postgres:14
    command: -c log_statement=all
    ports:
      - "54324:5432"
    environment:
      POSTGRES_DB: maasertracker
      POSTGRES_USER: maasertracker
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./docker/.pgdata:/var/lib/postgresql/data
    logging:
      driver: local
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MAASERTRACKER_DB_PORT: 5432
      MAASERTRACKER_DB_HOST: db
