addSbtPlugin("io.spray"                    % "sbt-revolver"             % "0.9.1")
addSbtPlugin("org.scala-js"                % "sbt-scalajs"              % "1.10.1")
addSbtPlugin("org.portable-scala"          % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("ch.epfl.scala"               % "sbt-scalajs-bundler"      % "0.20.0")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter"            % "1.0.0-beta39")
